version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-park-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: projectpark_db
      MYSQL_USER: marcot
      MYSQL_PASSWORD: 123456
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: